name: Generate

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0.0 # Optional fallback tag to use when no tag can be found
          prefix: v
          #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Print
        run: |
          echo "previousTag: ${{ steps.previoustag.outputs.tag }}"
          echo "milestone: ${{ steps.semvers.outputs.patch }}"
          echo "minor: ${{ steps.semvers.outputs.minor }}"
     
      - name: Update package.json version
        run: |
          tag_version=${{ steps.semvers.outputs.minor }}
          if [[ $tag_version == v* ]]; then
            tag_version="${tag_version#v}"
          fi
          jq ".version = \"$tag_version\"" package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Commit and push changes
        run: |
          git config --global user.name "nirlob"
          git config --global user.email "nirlob@users.noreply.github.com"
          git add package.json
#          git commit -m "chore: update package.json version to match tag ${{ steps.get_tag.outputs.tag }}"
#          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
