name: Update package.json Version from Latest Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          echo "Tag"
          echo $(git describe --tags --abbrev=0)
          echo "tag='$(git describe --tags --abbrev=0)'" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          tag_version=${{ steps.get_tag.outputs.tag }}
          if [[ $tag_version == v* ]]; then
            tag_version="${tag_version#v}"
          fi
          jq ".version = \"$tag_version\"" package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: update package.json version to match tag ${{ steps.get_tag.outputs.tag }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
